In [1]:
# Let's Setup the environment.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("You are good to go. Environment set-up done.")

You are good to go. Environment set-up done.

In [2]:
# Read the input file into a data frame.
rank_data = pd.read_csv("/kaggle/input/tseamcetlastrank/TSEAMCET_2022_finalphase.csv")

In [3]:
# Re-order the required columns to the start, and consider only the category required.

rank_data = rank_data[['INST CODE', 'INSTITUTE NAME', 'PLACE', 'DIST', 'COED', 'TYPE',
       'YEAR OF ESTB', 'BRANCH', 'BRANCH NAME', 'AFFILIATED','TUITION FEE ','OC GIRLS']]

#Re-Naming the category considered as the rank.

rank_data.rename(columns = {'OC GIRLS': 'RANK'},inplace=True)

# Sorting the data according to rank

rank_data = rank_data.sort_values(by=['RANK'],ignore_index=True)
rank_data.head()

,INST CODE,INSTITUTE NAME,PLACE,DIST,COED,TYPE,YEAR OF ESTB,BRANCH,BRANCH NAME,AFFILIATED,TUITION FEE,RANK
0,JNTH,JNTUH UNIVERSITY COLLEGE OF ENGG HYDERABAD,HYDERABAD,MDL,COED,UNIV,1965,CSE,COMPUTER SCIENCE AND ENGINEERING,JNTUH,50000,1685
1,CBIT,CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY,GANDIPET,RR,COED,PVT,1979,CSE,COMPUTER SCIENCE AND ENGINEERING,OU,140000,2219
2,CBIT,CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY,GANDIPET,RR,COED,PVT,1979,CSM,COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL I...,OU,140000,2507
3,VJEC,V N R VIGNANA JYOTHI INSTITUTE OF ENGG AND TECH,BACHUPALLY,MDL,COED,PVT,1995,CSE,COMPUTER SCIENCE AND ENGINEERING,JNTUH,135000,2595
4,VASV,VASAVI COLLEGE OF ENGINEERING,HYDERABAD,HYD,COED,PVT,1981,CSE,COMPUTER SCIENCE AND ENGINEERING,OU,140000,2675

In [4]:
# Collect all the unique districts in the list as we have to give that while filtering at the first page.

district = pd.Series(list(rank_data['DIST'].unique()))
district = district.sort_values(ignore_index=True)
district

0     HNK
1     HYD
2     JGN
3     JTL
4     KGM
5     KHM
6     KMR
7     KRM
8     MBN
9     MDL
10    MED
11    NLG
12    NZB
13    PDL
14     RR
15    SDP
16    SRC
17    SRD
18    SRP
19    WGL
20    WNP
21    YBG
dtype: object

##### **REFER THE BELOW TABLE TO FILTER OUT THE REQUIRED DISTRICTS**

|CODE|DISTRICT NAME|--|CODE|DISTRICT NAME|
|:--:|:------------|:---:|:---:|:----|
|HNK | HANAMAKONDA |--|JGN | JANGAON |
|HYD | HYDERABAD |--|YBG | YADADRI BHUVANGIRI |
|JTL | JAGITIAL |--|WNP | WANAPARTHY |
|KGM | HANAMAKONDA |--|WGL | WARANGAL |
|KHM | KHAMMAM |--|SRP | SURYAPET |
|KMR | KAMAREDDY |--|MBN | MAHABHUBNAGAR |
|KRM | KARIMNAGAR |--|NLG | NALGONDA |
|MDL | MEDCHAL |--|RR | RANGA REDYY |
|MED | MEDAK |--|SDP | SIDDIPET |
|NZB | NIZAMABAD |--|SRC | RAJANNA SIRICILLA |
|PDL | PEDDAPALLI |--|SRD | SANGAREDDY |

In [5]:
# Filtering the required districts

required_dist = district[district.index.isin([1,9,10,14])]
required_dist

1     HYD
9     MDL
10    MED
14     RR
dtype: object

##### **CATEGORIES AND SPECIALIZATIONS AVAILABLE AS PER TS-EAMCET**

|CATEGORY|BRANCH CODE|BRANCH NAME|--|CATEGORY|BRANCH CODE|BRANCH NAME|
|:------:|:---------:|:----------|--|:------:|:---------:|:----------|
|AEC|ANE|AERONATICAL ENGINEERING|--|AGE|AGR|AGRICULTURAL ENGINEERING|
|AEC|ARB|AUTOMATION AND ROBOTICS|--|AGE|BIO|BIO-TECHNOLOGY|
|AEC|AUT|AUTOMOBILE ENGINEERING|--|AGE|CHE|CHEMICAL ENGINEERING|
|AEC|BSE|BUILDING SERVICES ENGG|--|AGE|DRG|DAIRYING|
|AEC|CIV|CIVIL ENGINEERING|--|AGE|FDT|FOOD TECHNOLOGY|
|AEC|IPE|INDUSTRIAL PRODUCTION ENGG|--|AGE|GEO|GEO INFORMATICS|
|AEC|MCT|MECHTRONICS ENGINEERING|--|AGE|MIN|MINING ENGINEERING|
|AEC|MEC|MECHANICAL ENGINEERING|--|AGE|MMT|METALURGY AND MATERIAL ENGG|
|AEC|MET|METALLURGICAL ENGINEERING|--|AGE|PHE|PHARMACETICAL ENGINEERING|
|AEC|MMS|BTECH MECHINCAL WITH MTECHMANUFACTURING SYSTEMS|--|AGE|TEX|TEXTILE ENGINEERING|
|AEC|MTE|BTECH MECHANICAL WITH MTECH THERMAL ENGG|
|AEC|PLG|B.PLANNING|
----------------------------------------------------------------------------------------------------------------------------------------------------
|CATEGORY|BRANCH CODE|BRANCH NAME|--|CATEGORY|BRANCH CODE|BRANCH NAME|
|:------:|:---------:|:----------|--|:------:|:---------:|:----------|
|CRC|AI|ARITIFICIAL INTELLIGENCE|--|CIT|CME|COMPUTER ENGINEERING|
|CRC|AID|ARITIFICIAL INTELLIGENCE AND DATA SCIENCE|--|CIT|CSG|COMPUTER SCIENCE AND DESIGN|
|CRC|AIM|ARITIFICIAL INTELLIGENCE AND MACHINE LEARNING|--|CIT|CSN|COMPUTER SCIENCE AND ENGINEERING(NETWORKS)|
|CRC|CIC|IOT AND CYCBER SECURITY INCLUDING BLOCK CHAIN|--|CIT|CSO|COMPUTER SCIENCE AND ENGINEERING (IOT)|
|CRC|CSB|COMPUTER SCIENCE AND BUSINESS SYSTEM|--|CIT|CST|COMPUTER SCIENCE AND TECHNOLOGY|
|CRC|CSC|COMPUTER SCIENCE AND ENGINEERING(CYBER SECURITY)|--|CIT|CSW|COMPUTER ENGINEERING(SOFTWARE ENGINEERING)|
|CRC|CSD|COMPUTER SCIENCE AND ENGINEERING(DATA SCIENCE)|--|CIT|DTD|DIGITAL TECHNIQUES FOR DESIGN AND PLANNING|
|CRC|CSE|COMPUTER SCIENCE AND ENGINEERING(CYBER SECURITY)|--|CIT|INF|INFORMATION TECHNOLOGY|
|CRC|CSI|COMPUTER SCIENCE AND INFORMATION TECHNOLOGY|--|CIT|ITE|INFORMATION TECHNOLOGY AND ENGINEERING|
|CRC|CSM|COMPUTER SCIENCE AND ENGINEERING(AI AND ML)|
----------------------------------------------------------------------------------------------------------------------------------------------------
|CATEGORY|BRANCH CODE|BRANCH NAME|--|CATEGORY|BRANCH CODE|BRANCH NAME|
|:------:|:---------:|:----------|--|:------:|:---------:|:----------|
|ENG|BME|BIO-MEDICAL ENGINEERING|--|PHA|PHD|PHARM-D(M.P.C STREAM)|
|ENG|ECE|ELECTRONICS AND COMMUNICATION ENGINEERING|--|PHA|PHM|B.PHARMACY(M.P.C STREAM)|
|ENG|ECI|ELECTRONICS COMMUNICATION AND INSTRUMENTATION ENGINEERING|
|ENG|ECM|ELECTRONICS AND COMPUTER ENGINEERING|
|ENG|EEE|ELECTRICAL AND ELECTRONICS ENGINEERING|
|ENG|EIE|ELECTRONICS AND INTRUMENTATION ENGINEERING|
|ENG|ETM|ELECTRONICS AND TELEMATICS|

In [6]:
branches = pd.Series(list(rank_data['BRANCH NAME'].unique()))
branches = branches.sort_values(ignore_index=True)
print(branches)

0                              AERONAUTICAL ENGINEERING
1                              AGRICULTURAL ENGINEERING
2                               ARTIFICIAL INTELLIGENCE
3              ARTIFICIAL INTELLIGENCE AND DATA SCIENCE
4          ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING
5                                AUTOMOBILE ENGINEERING
6                           B. PHARMACY (M.P.C. STREAM)
7                               BIO-MEDICAL ENGINEERING
8                                        BIO-TECHNOLOGY
9     BTECH MECHANICAL WITH MTECH MANUFACTURING  SYS...
10             BTECH MECHANICAL WITH MTECH THERMAL ENGG
11                                 CHEMICAL ENGINEERING
12                                    CIVIL ENGINEERING
13                                 COMPUTER ENGINEERING
14           COMPUTER ENGINEERING(SOFTWARE ENGINEERING)
15                            COMPUTER SCIENCE & DESIGN
16            COMPUTER SCIENCE & ENGINEERING (NETWORKS)
17                 COMPUTER SCIENCE AND BUSINESS SYSTEM
18                     COMPUTER SCIENCE AND ENGINEERING
19    COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL I...
20    COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)
21      COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE)
22               COMPUTER SCIENCE AND ENGINEERING (IOT)
23         COMPUTER SCIENCE AND INFORMATION TECHNOLOGY
24                      COMPUTER SCIENCE AND TECHNOLOGY
25    CSE (IoT AND CYBER SECURITY INCLUDING BLOCK CH...
26                                             DAIRYING
27           DIGITAL TECHNIQUES FOR DESIGN AND PLANNING
28               ELECTRICAL AND ELECTRONICS ENGINEERING
29            ELECTRONICS AND COMMUNICATION ENGINEERING
30                 ELECTRONICS AND COMPUTER ENGINEERING
31          ELECTRONICS AND INSTRUMENTATION ENGINEERING
32                           ELECTRONICS AND TELEMATICS
33    ELECTRONICS COMMUNICATION AND INSTRUMENTATION ...
34                                      FOOD TECHNOLOGY
35                               INFORMATION TECHNOLOGY
36                 MECHANICAL (MECHTRONICS) ENGINEERING
37                               MECHANICAL ENGINEERING
38                            METALLURGICAL ENGINEERING
39                  METALLURGY AND MATERIAL ENGINEERING
40                                   MINING ENGINEERING
41                            PHARM - D (M.P.C. STREAM)
42                           PHARMACEUTICAL ENGINEERING
43                                             PLANNING
44                                   TEXTILE TECHNOLOGY
dtype: object

In [7]:
#Let's create a list of branches which student is intereseted in.
branches = branches[branches.index.isin([2,3,4,35,13,14,15,16,17,18,19,20,21,22,23,24,25])]
print(branches)

2                               ARTIFICIAL INTELLIGENCE
3              ARTIFICIAL INTELLIGENCE AND DATA SCIENCE
4          ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING
13                                 COMPUTER ENGINEERING
14           COMPUTER ENGINEERING(SOFTWARE ENGINEERING)
15                            COMPUTER SCIENCE & DESIGN
16            COMPUTER SCIENCE & ENGINEERING (NETWORKS)
17                 COMPUTER SCIENCE AND BUSINESS SYSTEM
18                     COMPUTER SCIENCE AND ENGINEERING
19    COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL I...
20    COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)
21      COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE)
22               COMPUTER SCIENCE AND ENGINEERING (IOT)
23         COMPUTER SCIENCE AND INFORMATION TECHNOLOGY
24                      COMPUTER SCIENCE AND TECHNOLOGY
25    CSE (IoT AND CYBER SECURITY INCLUDING BLOCK CH...
35                               INFORMATION TECHNOLOGY
dtype: object

In [8]:
# Filtering based on district
rank_data = rank_data[rank_data['DIST'].isin(list(required_dist))]

# Filtering based on branches
rank_data = rank_data[rank_data['BRANCH NAME'].isin(list(branches))]

# Drop the values where there are related courses or relevant data
rank_data = rank_data[rank_data['RANK'].notna()]

#Use the rank as a filter to get the college list for counselling.
final_college_list = rank_data[(rank_data['RANK'] > 10000) & (rank_data['RANK'] < 15000)]
final_college_list

#Filter based on any criteria like COED,TYPE,PLACE etc. and save it the final dataframe.

,INST CODE,INSTITUTE NAME,PLACE,DIST,COED,TYPE,YEAR OF ESTB,BRANCH,BRANCH NAME,AFFILIATED,TUITION FEE,RANK
61,VMEG,VARDHAMAN COLLEGE OF ENGINEERING,SHAMSHABAD,RR,COED,PVT,1999,AID,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,JNTUH,140000,10121
62,BVRI,B V RAJU INSTITUTE OF TECHNOLOGY,NARSAPUR,MED,COED,PVT,1997,CSD,COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE),JNTUH,135000,10225
63,MVSR,M V S R ENGINEERING COLLEGE (AUTONOMOUS),NADERGUL,RR,COED,PVT,1981,CSD,COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE),OU,130000,10365
64,CVSR,ANURAG UNIVERSITY (FORMERLY ANURAG GRP OF INST...,GHATKESAR,MDL,COED,PVT,2002,CSE,COMPUTER SCIENCE AND ENGINEERING,ANURAG UNIVERSITY,135000,10393
66,BVRI,B V RAJU INSTITUTE OF TECHNOLOGY,NARSAPUR,MED,COED,PVT,1997,INF,INFORMATION TECHNOLOGY,JNTUH,135000,10651
67,MGIT,MAHATMA GANDHI INSTITUTE OF TECHNOLOGY,GANDIPET,RR,COED,PVT,1997,INF,INFORMATION TECHNOLOGY,JNTUH,160000,10670
68,BVRW,BVRIT COLLEGE OF ENGINEERING FOR WOMEN,BACHUPALLY,MDL,GIRLS,PVT,2012,INF,INFORMATION TECHNOLOGY,JNTUH,120000,10687
70,MGIT,MAHATMA GANDHI INSTITUTE OF TECHNOLOGY,GANDIPET,RR,COED,PVT,1997,CSB,COMPUTER SCIENCE AND BUSINESS SYSTEM,JNTUH,160000,10794
71,IARE,INSTITUTE OF AERONAUTICAL ENGINEERING,DUNDIGAL,MDL,COED,PVT,2000,CSE,COMPUTER SCIENCE AND ENGINEERING,JNTUH,101000,10988
72,NGIT,NEIL GOGTE INST OF TECHNOLOGY,KACHIVANI SINGARAM,MDL,COED,PVT,2018,CSE,COMPUTER SCIENCE AND ENGINEERING,OU,90000,11022
73,BVRI,B V RAJU INSTITUTE OF TECHNOLOGY,NARSAPUR,MED,COED,PVT,1997,AID,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,JNTUH,135000,11260
74,SNIS,SRINIDHI INSTITUTE OF SCI AND TECHNOLOGY,GHATKESAR,MDL,COED,PVT,1997,CSC,COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY),JNTUH,130000,11264
75,VMEG,VARDHAMAN COLLEGE OF ENGINEERING,SHAMSHABAD,RR,COED,PVT,1999,AIM,ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING,JNTUH,140000,11344
76,SNIS,SRINIDHI INSTITUTE OF SCI AND TECHNOLOGY,GHATKESAR,MDL,COED,PVT,1997,INF,INFORMATION TECHNOLOGY,JNTUH,130000,11532
77,CMRK,C M R COLLEGE OF ENGG AND TECHNOLOGY (AUTONOMOUS),KANDLAKOYA,MDL,COED,PVT,2002,CSE,COMPUTER SCIENCE AND ENGINEERING,JNTUH,115000,11533
78,SNIS,SRINIDHI INSTITUTE OF SCI AND TECHNOLOGY,GHATKESAR,MDL,COED,PVT,1997,CSO,COMPUTER SCIENCE AND ENGINEERING (IOT),JNTUH,130000,11691
81,MVSR,M V S R ENGINEERING COLLEGE (AUTONOMOUS),NADERGUL,RR,COED,PVT,1981,CIC,CSE (IoT AND CYBER SECURITY INCLUDING BLOCK CH...,OU,130000,11951
85,VMEG,VARDHAMAN COLLEGE OF ENGINEERING,SHAMSHABAD,RR,COED,PVT,1999,INF,INFORMATION TECHNOLOGY,JNTUH,140000,12211
86,CVSR,ANURAG UNIVERSITY (FORMERLY ANURAG GRP OF INST...,GHATKESAR,MDL,COED,PVT,2002,AI,ARTIFICIAL INTELLIGENCE,ANURAG UNIVERSITY,135000,12319
87,NGIT,NEIL GOGTE INST OF TECHNOLOGY,KACHIVANI SINGARAM,MDL,COED,PVT,2018,CSM,COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL I...,OU,90000,12332
89,IARE,INSTITUTE OF AERONAUTICAL ENGINEERING,DUNDIGAL,MDL,COED,PVT,2000,CSM,COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL I...,JNTUH,101000,12458
92,BVRI,B V RAJU INSTITUTE OF TECHNOLOGY,NARSAPUR,MED,COED,PVT,1997,CSB,COMPUTER SCIENCE AND BUSINESS SYSTEM,JNTUH,135000,12839
93,MVSR,M V S R ENGINEERING COLLEGE (AUTONOMOUS),NADERGUL,RR,COED,PVT,1981,INF,INFORMATION TECHNOLOGY,OU,130000,12950
95,CMRK,C M R COLLEGE OF ENGG AND TECHNOLOGY (AUTONOMOUS),KANDLAKOYA,MDL,COED,PVT,2002,CSM,COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL I...,JNTUH,115000,13213
97,BREW,BHOJREDDY ENGINEERING COLLEGE FOR WOMEN,SAIDABAD,HYD,GIRLS,PVT,1997,CSE,COMPUTER SCIENCE AND ENGINEERING,JNTUH,75000,13684
98,MECS,MATRUSRI ENGINEERING COLLEGE,HYDERABAD,HYD,COED,PVT,2011,CSE,COMPUTER SCIENCE AND ENGINEERING,OU,100000,13717
100,CMRK,C M R COLLEGE OF ENGG AND TECHNOLOGY (AUTONOMOUS),KANDLAKOYA,MDL,COED,PVT,2002,CSD,COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE),JNTUH,115000,14035
101,IARE,INSTITUTE OF AERONAUTICAL ENGINEERING,DUNDIGAL,MDL,COED,PVT,2000,CSD,COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE),JNTUH,101000,14213
106,IARE,INSTITUTE OF AERONAUTICAL ENGINEERING,DUNDIGAL,MDL,COED,PVT,2000,CSC,COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY),JNTUH,101000,14822

In [9]:
final_college_list.to_csv('Final_College_List',encoding='utf-8',index=False)